name: use deps

on:
  workflow_dispatch:
    inputs: 
      unused:
        description: 'unused dummy input'
        required: false
        default: "unused"

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    - name: Download deps
      uses: actions/download-artifact@v2
      with:
        name: jw3126/toydeps/deps
        path: ~/deps.tar.gz

    - name: Use deps
      run: ./use_deps.yml
