name: use deps

on:
  workflow_dispatch:
    inputs: 
      unused:
        description: 'unused dummy input'
        required: false
        default: "unused"

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: Download deps
      # uses: actions/download-artifact@v2
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: build_deps.yml
        workflow_conclusion: success
        repo: jw3126/toydeps2
        name: deps
        path: deps

    - name: Use deps
      run: |
        ./use_deps.sh
